/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    800: '#1e40af',
                    900: '#1e3a8a',
                    950: '#172554',
                },
                secondary: {
                    50: '#f8fafc',
                    100: '#f1f5f9',
                    200: '#e2e8f0',
                    300: '#cbd5e1',
                    400: '#94a3b8',
                    500: '#64748b',
                    600: '#475569',
                    700: '#334155',
                    800: '#1e293b',
                    900: '#0f172a',
                    950: '#020617',
                },
                accent: {
                    50: '#fdf4ff',
                    100: '#fae8ff',
                    200: '#f5d0fe',
                    300: '#f0abfc',
                    400: '#e879f9',
                    500: '#d946ef',
                    600: '#c026d3',
                    700: '#a21caf',
                    800: '#86198f',
                    900: '#701a75',
                    950: '#4a044e',
                },
                success: {
                    50: '#f0fdf4',
                    100: '#dcfce7',
                    200: '#bbf7d0',
                    300: '#86efac',
                    400: '#4ade80',
                    500: '#22c55e',
                    600: '#16a34a',
                    700: '#15803d',
                    800: '#166534',
                    900: '#14532d',
                    950: '#052e16',
                },
                warning: {
                    50: '#fffbeb',
                    100: '#fef3c7',
                    200: '#fde68a',
                    300: '#fcd34d',
                    400: '#fbbf24',
                    500: '#f59e0b',
                    600: '#d97706',
                    700: '#b45309',
                    800: '#92400e',
                    900: '#78350f',
                    950: '#451a03',
                },
                error: {
                    50: '#fef2f2',
                    100: '#fee2e2',
                    200: '#fecaca',
                    300: '#fca5a5',
                    400: '#f87171',
                    500: '#ef4444',
                    600: '#dc2626',
                    700: '#b91c1c',
                    800: '#991b1b',
                    900: '#7f1d1d',
                    950: '#450a0a',
                },
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                mono: ['JetBrains Mono', 'monospace'],
                display: ['Poppins', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                'xs': ['0.75rem', { lineHeight: '1rem' }],
                'sm': ['0.875rem', { lineHeight: '1.25rem' }],
                'base': ['1rem', { lineHeight: '1.5rem' }],
                'lg': ['1.125rem', { lineHeight: '1.75rem' }],
                'xl': ['1.25rem', { lineHeight: '1.75rem' }],
                '2xl': ['1.5rem', { lineHeight: '2rem' }],
                '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
                '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
                '5xl': ['3rem', { lineHeight: '1' }],
                '6xl': ['3.75rem', { lineHeight: '1' }],
                '7xl': ['4.5rem', { lineHeight: '1' }],
                '8xl': ['6rem', { lineHeight: '1' }],
                '9xl': ['8rem', { lineHeight: '1' }],
            },
            spacing: {
                '18': '4.5rem',
                '88': '22rem',
                '128': '32rem',
                '144': '36rem',
            },
            borderRadius: {
                '4xl': '2rem',
                '5xl': '2.5rem',
                '6xl': '3rem',
            },
            animation: {
                'fade-in': 'fadeIn 0.5s ease-in-out',
                'fade-out': 'fadeOut 0.5s ease-in-out',
                'slide-in-up': 'slideInUp 0.5s ease-out',
                'slide-in-down': 'slideInDown 0.5s ease-out',
                'slide-in-left': 'slideInLeft 0.5s ease-out',
                'slide-in-right': 'slideInRight 0.5s ease-out',
                'scale-in': 'scaleIn 0.3s ease-out',
                'scale-out': 'scaleOut 0.3s ease-out',
                'bounce-in': 'bounceIn 0.6s ease-out',
                'bounce-out': 'bounceOut 0.6s ease-out',
                'rotate-in': 'rotateIn 0.5s ease-out',
                'rotate-out': 'rotateOut 0.5s ease-out',
                'flip-in': 'flipIn 0.6s ease-out',
                'flip-out': 'flipOut 0.6s ease-out',
                'hinge': 'hinge 2s ease-in-out',
                'jack-in-the-box': 'jackInTheBox 1s ease-out',
                'roll-in': 'rollIn 0.6s ease-out',
                'roll-out': 'rollOut 0.6s ease-out',
                'zoom-in': 'zoomIn 0.3s ease-out',
                'zoom-out': 'zoomOut 0.3s ease-out',
                'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'ping': 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
                'bounce': 'bounce 1s infinite',
                'spin': 'spin 1s linear infinite',
                'wiggle': 'wiggle 1s ease-in-out infinite',
                'float': 'float 3s ease-in-out infinite',
                'glow': 'glow 2s ease-in-out infinite alternate',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                fadeOut: {
                    '0%': { opacity: '1' },
                    '100%': { opacity: '0' },
                },
                slideInUp: {
                    '0%': { transform: 'translateY(100%)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideInDown: {
                    '0%': { transform: 'translateY(-100%)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideInLeft: {
                    '0%': { transform: 'translateX(-100%)', opacity: '0' },
                    '100%': { transform: 'translateX(0)', opacity: '1' },
                },
                slideInRight: {
                    '0%': { transform: 'translateX(100%)', opacity: '0' },
                    '100%': { transform: 'translateX(0)', opacity: '1' },
                },
                scaleIn: {
                    '0%': { transform: 'scale(0)', opacity: '0' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                scaleOut: {
                    '0%': { transform: 'scale(1)', opacity: '1' },
                    '100%': { transform: 'scale(0)', opacity: '0' },
                },
                bounceIn: {
                    '0%': { transform: 'scale(0.3)', opacity: '0' },
                    '50%': { transform: 'scale(1.05)' },
                    '70%': { transform: 'scale(0.9)' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                bounceOut: {
                    '0%': { transform: 'scale(1)', opacity: '1' },
                    '20%': { transform: 'scale(0.9)' },
                    '50%': { transform: 'scale(1.1)' },
                    '100%': { transform: 'scale(0.3)', opacity: '0' },
                },
                rotateIn: {
                    '0%': { transform: 'rotate(-200deg)', opacity: '0' },
                    '100%': { transform: 'rotate(0)', opacity: '1' },
                },
                rotateOut: {
                    '0%': { transform: 'rotate(0)', opacity: '1' },
                    '100%': { transform: 'rotate(200deg)', opacity: '0' },
                },
                flipIn: {
                    '0%': { transform: 'perspective(400px) rotateY(90deg)', opacity: '0' },
                    '40%': { transform: 'perspective(400px) rotateY(-20deg)' },
                    '60%': { transform: 'perspective(400px) rotateY(10deg)' },
                    '80%': { transform: 'perspective(400px) rotateY(-5deg)' },
                    '100%': { transform: 'perspective(400px) rotateY(0deg)', opacity: '1' },
                },
                flipOut: {
                    '0%': { transform: 'perspective(400px) rotateY(0deg)', opacity: '1' },
                    '100%': { transform: 'perspective(400px) rotateY(-90deg)', opacity: '0' },
                },
                hinge: {
                    '0%': { transform: 'rotate(0)', transformOrigin: 'top left', animationTimingFunction: 'ease-in-out' },
                    '20%, 60%': { transform: 'rotate(80deg)', transformOrigin: 'top left', animationTimingFunction: 'ease-in-out' },
                    '40%, 80%': { transform: 'rotate(60deg)', transformOrigin: 'top left', animationTimingFunction: 'ease-in-out' },
                    '100%': { transform: 'rotate(60deg)', transformOrigin: 'top left', animationTimingFunction: 'ease-in-out' },
                },
                jackInTheBox: {
                    '0%': { opacity: '0', transform: 'scale(0.1) rotate(30deg)', transformOrigin: 'center bottom' },
                    '50%': { transform: 'rotate(-10deg)' },
                    '70%': { transform: 'rotate(3deg)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                rollIn: {
                    '0%': { opacity: '0', transform: 'translate3d(-100%, 0, 0) rotate3d(0, 0, 1, -120deg)' },
                    '100%': { opacity: '1', transform: 'translate3d(0, 0, 0)' },
                },
                rollOut: {
                    '0%': { opacity: '1', transform: 'translate3d(0, 0, 0)' },
                    '100%': { opacity: '0', transform: 'translate3d(100%, 0, 0) rotate3d(0, 0, 1, 120deg)' },
                },
                zoomIn: {
                    '0%': { opacity: '0', transform: 'scale3d(0.3, 0.3, 0.3)' },
                    '50%': { opacity: '1' },
                },
                zoomOut: {
                    '0%': { opacity: '1' },
                    '50%': { opacity: '0', transform: 'scale3d(0.3, 0.3, 0.3)' },
                    '100%': { opacity: '0' },
                },
                wiggle: {
                    '0%, 100%': { transform: 'translateX(0)' },
                    '10%': { transform: 'translateX(-9px)' },
                    '20%': { transform: 'translateX(8px)' },
                    '30%': { transform: 'translateX(-7px)' },
                    '40%': { transform: 'translateX(6px)' },
                    '50%': { transform: 'translateX(-5px)' },
                    '60%': { transform: 'translateX(4px)' },
                    '70%': { transform: 'translateX(-3px)' },
                    '80%': { transform: 'translateX(2px)' },
                    '90%': { transform: 'translateX(-1px)' },
                },
                float: {
                    '0%, 100%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-20px)' },
                },
                glow: {
                    '0%': { boxShadow: '0 0 5px #3b82f6, 0 0 10px #3b82f6, 0 0 15px #3b82f6' },
                    '100%': { boxShadow: '0 0 10px #3b82f6, 0 0 20px #3b82f6, 0 0 30px #3b82f6' },
                },
            },
            backdropBlur: {
                xs: '2px',
            },
            boxShadow: {
                'inner-lg': 'inset 0 2px 4px 0 rgb(0 0 0 / 0.06)',
                'glow': '0 0 20px rgba(59, 130, 246, 0.5)',
                'glow-lg': '0 0 40px rgba(59, 130, 246, 0.3)',
                'glow-xl': '0 0 60px rgba(59, 130, 246, 0.2)',
            },
            transitionProperty: {
                'height': 'height',
                'spacing': 'margin, padding',
            },
        },
    },
    plugins: [],
}
